import { Migration } from '@mikro-orm/migrations';

export class Migration20260918145559_pricing_engine extends Migration {

  override up(): void | Promise<void> {
    this.addSql(`create table "pricing_calculations" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "created_at" timestamptz not null, "customer_id" uuid null, "currency_code" text not null, "context_snapshot" jsonb not null, "final_unit_price_net" numeric(18,4) not null default '0', "final_total_net" numeric(18,4) not null default '0', "total_cost_net" numeric(18,4) not null default '0', "markup_percent" numeric(7,4) not null default '0', "margin_percent" numeric(7,4) not null default '0', "mode" text not null default 'shadow', "parameter_set_version" int not null default 1, "triggered_by" text not null default 'api', "triggered_by_user_id" uuid null, "duration_ms" int not null default 0, "warnings" jsonb null, "calculated_at" timestamptz not null, "is_demo" boolean not null default false, primary key ("id"));`);
    this.addSql(`create index "pricing_calculations_customer_idx" on "pricing_calculations" ("tenant_id", "organization_id", "customer_id");`);
    this.addSql(`create index "pricing_calculations_scope_idx" on "pricing_calculations" ("tenant_id", "organization_id", "calculated_at");`);

    this.addSql(`create table "pricing_calculation_lines" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "created_at" timestamptz not null, "calculation_id" uuid not null, "basket_line_index" int not null default 0, "component_code" text not null, "position" int not null, "effect" text not null, "value" numeric(18,6) not null default '0', "running_total" numeric(18,4) not null default '0', "inputs" jsonb null, "params" jsonb null, "explain_key" text not null, "explain_values" jsonb null, "confidence" text not null default 'default', "warnings" jsonb null, primary key ("id"));`);
    this.addSql(`create index "pricing_calculation_lines_calculation_idx" on "pricing_calculation_lines" ("tenant_id", "calculation_id", "position");`);

    this.addSql(`create table "pricing_components" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "code" text not null, "label_key" text not null, "position" int not null, "effect" text not null, "level" text not null default 'line', "is_active" boolean not null default true, primary key ("id"));`);
    this.addSql(`alter table "pricing_components" add constraint "pricing_components_code_unique" unique ("tenant_id", "organization_id", "code");`);

    this.addSql(`create table "pricing_component_params" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "component_code" text not null, "scope" text not null default 'global', "scope_ref_id" text null, "payload" jsonb not null, "valid_from" timestamptz not null, "valid_to" timestamptz null, "created_by_user_id" uuid null, "change_note" text null, primary key ("id"));`);
    this.addSql(`create index "pricing_component_params_lookup_idx" on "pricing_component_params" ("tenant_id", "organization_id", "component_code", "scope");`);

    this.addSql(`create table "pricing_coverage_entries" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "component_code" text not null, "source_kind" text not null, "source_ref" text null, "freshness_days" int null, "confidence" text not null default 'default', "missing_reason_key" text null, "last_checked_at" timestamptz null, primary key ("id"));`);
    this.addSql(`alter table "pricing_coverage_entries" add constraint "pricing_coverage_entries_component_unique" unique ("tenant_id", "organization_id", "component_code");`);

    this.addSql(`create table "pricing_customer_indicators" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "customer_id" uuid not null, "code" text not null, "value" numeric(18,6) not null default '0', "normalized_value" numeric(7,4) not null default '0', "window_from" timestamptz null, "window_to" timestamptz null, "computed_at" timestamptz not null, "algorithm_version" int not null default 1, "confidence" text not null default 'estimated', primary key ("id"));`);
    this.addSql(`create index "pricing_customer_indicators_lookup_idx" on "pricing_customer_indicators" ("tenant_id", "organization_id", "customer_id", "code");`);

    this.addSql(`create table "pricing_customer_indicator_definitions" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "code" text not null, "label_key" text not null, "description_key" text null, "direction" text not null, "weight" numeric(7,4) not null default '0', "algorithm_version" int not null default 1, "source" text null, "is_active" boolean not null default true, primary key ("id"));`);
    this.addSql(`alter table "pricing_customer_indicator_definitions" add constraint "pricing_customer_indicator_definitions_code_unique" unique ("tenant_id", "organization_id", "code");`);

    this.addSql(`create table "pricing_customer_profiles" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "customer_id" uuid not null, "customer_group_code" text null, "delivery_zone_code" text null, "default_order_scenario_code" text null, "negotiated_prices" jsonb null, "negotiated_price_expires_at" timestamptz null, primary key ("id"));`);
    this.addSql(`alter table "pricing_customer_profiles" add constraint "pricing_customer_profiles_customer_unique" unique ("tenant_id", "organization_id", "customer_id");`);

    this.addSql(`create table "pricing_delivery_zones" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "code" text not null, "label" text not null, "avg_distance_km" numeric(18,4) not null, "avg_drive_minutes" numeric(18,4) not null, "typical_stops" int not null default 1, "default_vehicle_code" text null, primary key ("id"));`);
    this.addSql(`create index "pricing_delivery_zones_scope_idx" on "pricing_delivery_zones" ("tenant_id", "organization_id", "code");`);

    this.addSql(`create table "pricing_fuel_prices" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "fuel_type" text not null, "price_per_litre" numeric(18,4) not null, "observed_on" timestamptz not null, primary key ("id"));`);
    this.addSql(`create index "pricing_fuel_prices_scope_idx" on "pricing_fuel_prices" ("tenant_id", "organization_id", "fuel_type", "observed_on");`);

    this.addSql(`create table "pricing_guardrails" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "code" text not null, "min_margin_percent" numeric(7,4) null, "max_discount_percent" numeric(7,4) null, "floor_price" numeric(18,4) null, "rounding" jsonb null, "negotiated_price_precedence" text not null default 'negotiated_wins', "scope" text not null default 'global', "scope_ref_id" text null, "valid_from" timestamptz not null, "valid_to" timestamptz null, primary key ("id"));`);
    this.addSql(`create index "pricing_guardrails_lookup_idx" on "pricing_guardrails" ("tenant_id", "organization_id", "scope");`);

    this.addSql(`create table "pricing_labor_rates" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "role_code" text not null, "label" text not null, "hourly_rate" numeric(18,4) not null, "overhead_rate" numeric(7,4) not null default '0', "valid_from" timestamptz not null, "valid_to" timestamptz null, primary key ("id"));`);
    this.addSql(`create index "pricing_labor_rates_scope_idx" on "pricing_labor_rates" ("tenant_id", "organization_id", "role_code");`);

    this.addSql(`create table "pricing_order_scenarios" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "code" text not null, "label" text not null, "step_multipliers" jsonb null, "extra_step_codes" jsonb null, "valid_from" timestamptz not null, "valid_to" timestamptz null, primary key ("id"));`);
    this.addSql(`create index "pricing_order_scenarios_scope_idx" on "pricing_order_scenarios" ("tenant_id", "organization_id", "code");`);

    this.addSql(`create table "pricing_packaging_costs" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "unit_code" text not null, "material_cost" numeric(18,4) not null, "pack_minutes" numeric(18,4) not null, "role_code" text not null, "valid_from" timestamptz not null, "valid_to" timestamptz null, primary key ("id"));`);
    this.addSql(`create index "pricing_packaging_costs_scope_idx" on "pricing_packaging_costs" ("tenant_id", "organization_id", "unit_code");`);

    this.addSql(`create table "pricing_process_steps" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "code" text not null, "label" text not null, "role_code" text not null, "duration_minutes" numeric(18,4) not null, "is_per_line" boolean not null default false, "is_per_order" boolean not null default true, "valid_from" timestamptz not null, "valid_to" timestamptz null, primary key ("id"));`);
    this.addSql(`create index "pricing_process_steps_scope_idx" on "pricing_process_steps" ("tenant_id", "organization_id", "code");`);

    this.addSql(`create table "pricing_purchase_positions" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "catalog_product_id" uuid not null, "catalog_variant_id" uuid null, "sku" text null, "annual_volume" numeric(18,4) not null default '0', "current_tier_code" text null, "current_tier_discount" numeric(7,4) not null default '0', "next_tier_volume" numeric(18,4) null, "next_tier_discount" numeric(7,4) null, "last_delivery_unit_cost" numeric(18,4) null, "last_delivery_at" timestamptz null, "last_delivery_quantity" numeric(18,4) null, "sold_quantity_period" numeric(18,4) null, "product_group_code" text null, primary key ("id"));`);
    this.addSql(`create index "pricing_purchase_positions_product_idx" on "pricing_purchase_positions" ("tenant_id", "organization_id", "catalog_product_id");`);

    this.addSql(`create table "pricing_shadow_observations" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "created_at" timestamptz not null, "calculation_id" uuid null, "customer_id" uuid null, "sales_document_kind" text null, "sales_document_id" uuid null, "sales_line_id" uuid null, "invoiced_unit_price_net" numeric(18,4) not null default '0', "engine_unit_price_net" numeric(18,4) not null default '0', "delta_absolute" numeric(18,4) not null default '0', "delta_percent" numeric(7,4) not null default '0', "observed_at" timestamptz not null, primary key ("id"));`);
    this.addSql(`create index "pricing_shadow_observations_scope_idx" on "pricing_shadow_observations" ("tenant_id", "organization_id", "observed_at");`);

    this.addSql(`create table "pricing_supplier_profiles" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "slug" text not null, "name" text not null, "currency_code" text not null, "default_target_markup" numeric(7,4) not null default '0', "mode" text not null default 'shadow', "rounding_policy" jsonb null, "parameter_set_version" int not null default 1, primary key ("id"));`);
    this.addSql(`alter table "pricing_supplier_profiles" add constraint "pricing_supplier_profiles_slug_unique" unique ("tenant_id", "organization_id", "slug");`);

    this.addSql(`create table "pricing_vehicles" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "code" text not null, "label" text not null, "capacity_kg" numeric(18,4) null, "capacity_m3" numeric(18,4) null, "capacity_pallets" int null, "fuel_type" text not null, "consumption_l_per_100km" numeric(18,4) not null, "fixed_cost_month" numeric(18,4) not null default '0', "driver_role_code" text not null, "is_active" boolean not null default true, primary key ("id"));`);
    this.addSql(`create index "pricing_vehicles_scope_idx" on "pricing_vehicles" ("tenant_id", "organization_id", "code");`);

    this.addSql(`create table "pricing_warehouse_costs" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "is_demo" boolean not null default false, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "basis" text not null, "cost_per_month" numeric(18,4) not null, "capital_cost_annual_rate" numeric(7,4) not null default '0', "default_turnover_days" int not null default 30, "valid_from" timestamptz not null, "valid_to" timestamptz null, primary key ("id"));`);
    this.addSql(`create index "pricing_warehouse_costs_scope_idx" on "pricing_warehouse_costs" ("tenant_id", "organization_id", "basis");`);
  }

}
