/**
 * Seed data for the HoReCa customer base of a Polish B2B wholesale distributor
 * (cleaning chemicals, packaging, paper) dispatching from a depot in Warszawa.
 *
 * Coordinates are real values for the named towns: the pricing engine derives the
 * delivery cost from the great-circle distance between HORECA_DEPOT and the
 * delivery address, so they are load-bearing.
 *
 * Monetary and geographic values are decimal strings to avoid float drift.
 */

export type HorecaDeliveryZoneCode =
  | 'warszawa-centrum'
  | 'warszawa-obrzeza'
  | 'mazowieckie-blisko'
  | 'mazowieckie-daleko'

export type HorecaOrderScenarioCode =
  | 'ideal_file'
  | 'nonstandard_file'
  | 'phone'
  | 'sms'
  | 'email'
  | 'rep_visit'

export type HorecaCustomerSegment =
  | 'restauracja'
  | 'hotel'
  | 'stolowka'
  | 'kawiarnia'
  | 'catering'
  | 'piekarnia'
  | 'szpital'
  | 'szkola'

export type HorecaDeliveryAddressSeed = {
  label: string
  line1: string
  line2?: string
  city: string
  postalCode: string
  region: string
  countryCode: string
  latitude: string
  longitude: string
  isDefault?: boolean
}

export type HorecaCustomerSeed = {
  handle: string
  companyName: string
  segment: HorecaCustomerSegment
  taxId: string
  email: string
  phone: string
  contactPerson: string
  deliveryZoneCode: HorecaDeliveryZoneCode
  orderScenarioCode: HorecaOrderScenarioCode
  monthlyOrderCount: number
  avgBasketValueNet: string
  paymentTermDays: number
  addresses: HorecaDeliveryAddressSeed[]
}

export type HorecaDepotSeed = {
  label: string
  line1: string
  city: string
  postalCode: string
  region: string
  countryCode: string
  latitude: string
  longitude: string
}

export const HORECA_DEPOT: HorecaDepotSeed = {
  label: 'Magazyn centralny',
  line1: 'ul. Towarowa 22',
  city: 'Warszawa',
  postalCode: '00-839',
  region: 'mazowieckie',
  countryCode: 'PL',
  latitude: '52.229700',
  longitude: '21.012200',
}

export const HORECA_CUSTOMERS: HorecaCustomerSeed[] = [
  {
    handle: 'horeca-stara-kuznia',
    companyName: 'Restauracja Stara Kuźnia sp. z o.o.',
    segment: 'restauracja',
    taxId: '5251036216',
    email: 'zamowienia@starakuznia.pl',
    phone: '+48 22 621 48 12',
    contactPerson: 'Marek Wiśniewski',
    deliveryZoneCode: 'warszawa-centrum',
    orderScenarioCode: 'phone',
    monthlyOrderCount: 6,
    avgBasketValueNet: '1240.50',
    paymentTermDays: 14,
    addresses: [
      {
        label: 'Kuchnia główna',
        line1: 'ul. Nowy Świat 42',
        line2: 'Śródmieście',
        city: 'Warszawa',
        postalCode: '00-363',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.234000',
        longitude: '21.021000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-hotel-wislany-brzeg',
    companyName: 'Hotel Wiślany Brzeg sp. z o.o.',
    segment: 'hotel',
    taxId: '5272418816',
    email: 'zaopatrzenie@wislanybrzeg.pl',
    phone: '+48 22 583 19 40',
    contactPerson: 'Agnieszka Lewandowska',
    deliveryZoneCode: 'warszawa-centrum',
    orderScenarioCode: 'ideal_file',
    monthlyOrderCount: 11,
    avgBasketValueNet: '6180.00',
    paymentTermDays: 30,
    addresses: [
      {
        label: 'Magazyn hotelowy',
        line1: 'ul. Solec 81',
        line2: 'Powiśle',
        city: 'Warszawa',
        postalCode: '00-382',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.234000',
        longitude: '21.040000',
        isDefault: true,
      },
      {
        label: 'Kuchnia restauracji hotelowej',
        line1: 'ul. Zamoyskiego 45',
        line2: 'Praga-Południe',
        city: 'Warszawa',
        postalCode: '03-801',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.247000',
        longitude: '21.055000',
      },
    ],
  },
  {
    handle: 'horeca-kawiarnia-bez-cukru',
    companyName: 'Kawiarnia Bez Cukru Anna Wójcik',
    segment: 'kawiarnia',
    taxId: '7010345129',
    email: 'kontakt@bezcukru.waw.pl',
    phone: '+48 604 218 337',
    contactPerson: 'Anna Wójcik',
    deliveryZoneCode: 'warszawa-centrum',
    orderScenarioCode: 'sms',
    monthlyOrderCount: 3,
    avgBasketValueNet: '412.80',
    paymentTermDays: 0,
    addresses: [
      {
        label: 'Lokal',
        line1: 'ul. Mokotowska 12',
        line2: 'Śródmieście',
        city: 'Warszawa',
        postalCode: '00-561',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.223000',
        longitude: '21.018000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-stolowka-ministerialna',
    companyName: 'Stołówka Ministerialna sp. z o.o.',
    segment: 'stolowka',
    taxId: '5261859741',
    email: 'biuro@stolowkaministerialna.pl',
    phone: '+48 22 455 07 21',
    contactPerson: 'Beata Kaczmarek',
    deliveryZoneCode: 'warszawa-centrum',
    orderScenarioCode: 'nonstandard_file',
    monthlyOrderCount: 6,
    avgBasketValueNet: '2340.00',
    paymentTermDays: 30,
    addresses: [
      {
        label: 'Kuchnia główna',
        line1: 'ul. Wspólna 62',
        line2: 'Śródmieście',
        city: 'Warszawa',
        postalCode: '00-684',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.227000',
        longitude: '21.014000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-catering-srodmiescie',
    companyName: 'Catering Śródmieście Marek Zieliński',
    segment: 'catering',
    taxId: '5224103368',
    email: 'zamowienia@cateringsrodmiescie.pl',
    phone: '+48 508 774 190',
    contactPerson: 'Marek Zieliński',
    deliveryZoneCode: 'warszawa-centrum',
    orderScenarioCode: 'nonstandard_file',
    monthlyOrderCount: 9,
    avgBasketValueNet: '3120.40',
    paymentTermDays: 21,
    addresses: [
      {
        label: 'Kuchnia produkcyjna',
        line1: 'ul. Żelazna 59',
        line2: 'Wola',
        city: 'Warszawa',
        postalCode: '00-848',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.232000',
        longitude: '20.997000',
        isDefault: true,
      },
      {
        label: 'Kuchnia pomocnicza',
        line1: 'ul. Ordona 7',
        line2: 'Wola',
        city: 'Warszawa',
        postalCode: '01-237',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.228000',
        longitude: '20.970000',
      },
    ],
  },
  {
    handle: 'horeca-piekarnia-zloty-bochen',
    companyName: 'Piekarnia Złoty Bochen sp.j.',
    segment: 'piekarnia',
    taxId: '5252391178',
    email: 'zaopatrzenie@zlotybochen.pl',
    phone: '+48 22 668 34 55',
    contactPerson: 'Tomasz Dąbrowski',
    deliveryZoneCode: 'warszawa-centrum',
    orderScenarioCode: 'phone',
    monthlyOrderCount: 10,
    avgBasketValueNet: '980.60',
    paymentTermDays: 14,
    addresses: [
      {
        label: 'Zaplecze piekarni',
        line1: 'ul. Grójecka 77',
        line2: 'Ochota',
        city: 'Warszawa',
        postalCode: '02-094',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.215000',
        longitude: '20.985000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-szpital-wolski',
    companyName: 'Szpital Wolski Dział Żywienia',
    segment: 'szpital',
    taxId: '5270207423',
    email: 'zywienie@szpitalwolski.pl',
    phone: '+48 22 389 21 60',
    contactPerson: 'Jolanta Szymańska',
    deliveryZoneCode: 'warszawa-centrum',
    orderScenarioCode: 'ideal_file',
    monthlyOrderCount: 12,
    avgBasketValueNet: '8450.00',
    paymentTermDays: 45,
    addresses: [
      {
        label: 'Kuchnia centralna',
        line1: 'ul. Kasprzaka 17',
        line2: 'Wola',
        city: 'Warszawa',
        postalCode: '01-211',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.236100',
        longitude: '20.966000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-liceum-praskie',
    companyName: 'Liceum Praskie im. Władysława Reymonta',
    segment: 'szkola',
    taxId: '1132098462',
    email: 'administracja@liceumpraskie.edu.pl',
    phone: '+48 22 619 55 04',
    contactPerson: 'Piotr Grabowski',
    deliveryZoneCode: 'warszawa-centrum',
    orderScenarioCode: 'email',
    monthlyOrderCount: 4,
    avgBasketValueNet: '1680.00',
    paymentTermDays: 30,
    addresses: [
      {
        label: 'Budynek główny',
        line1: 'ul. Targowa 66',
        line2: 'Praga-Północ',
        city: 'Warszawa',
        postalCode: '03-734',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.254000',
        longitude: '21.035000',
        isDefault: true,
      },
      {
        label: 'Filia dydaktyczna',
        line1: 'ul. Otwocka 3',
        line2: 'Praga-Północ',
        city: 'Warszawa',
        postalCode: '03-759',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.257000',
        longitude: '21.045000',
      },
    ],
  },
  {
    handle: 'horeca-bistro-saska-kepa',
    companyName: 'Bistro Saska Kępa Ewa Nowak',
    segment: 'restauracja',
    taxId: '1130172266',
    email: 'biuro@bistrosaska.pl',
    phone: '+48 691 402 118',
    contactPerson: 'Ewa Nowak',
    deliveryZoneCode: 'warszawa-centrum',
    orderScenarioCode: 'sms',
    monthlyOrderCount: 5,
    avgBasketValueNet: '860.20',
    paymentTermDays: 7,
    addresses: [
      {
        label: 'Kuchnia',
        line1: 'ul. Francuska 24',
        line2: 'Saska Kępa',
        city: 'Warszawa',
        postalCode: '03-906',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.238000',
        longitude: '21.060000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-hotel-zoliborz-residence',
    companyName: 'Hotel Żoliborz Residence sp. z o.o.',
    segment: 'hotel',
    taxId: '5258154031',
    email: 'zakupy@zoliborzresidence.pl',
    phone: '+48 22 833 70 88',
    contactPerson: 'Katarzyna Pawlak',
    deliveryZoneCode: 'warszawa-centrum',
    orderScenarioCode: 'email',
    monthlyOrderCount: 8,
    avgBasketValueNet: '4270.90',
    paymentTermDays: 21,
    addresses: [
      {
        label: 'Magazyn gospodarczy',
        line1: 'ul. Krasińskiego 20',
        line2: 'Żoliborz',
        city: 'Warszawa',
        postalCode: '01-581',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.269000',
        longitude: '20.984000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-kawiarnia-mokotowska-palarnia',
    companyName: 'Mokotowska Palarnia Kawy sp. z o.o.',
    segment: 'kawiarnia',
    taxId: '5213680926',
    email: 'sklep@mokotowskapalarnia.pl',
    phone: '+48 733 561 204',
    contactPerson: 'Michał Adamczyk',
    deliveryZoneCode: 'warszawa-centrum',
    orderScenarioCode: 'phone',
    monthlyOrderCount: 4,
    avgBasketValueNet: '625.30',
    paymentTermDays: 7,
    addresses: [
      {
        label: 'Palarnia i kawiarnia',
        line1: 'ul. Puławska 39',
        line2: 'Mokotów',
        city: 'Warszawa',
        postalCode: '02-508',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.191700',
        longitude: '21.040000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-restauracja-bielanska-chata',
    companyName: 'Restauracja Bielańska Chata sp.j.',
    segment: 'restauracja',
    taxId: '1180945374',
    email: 'zamowienia@bielanskachata.pl',
    phone: '+48 22 834 12 77',
    contactPerson: 'Robert Jankowski',
    deliveryZoneCode: 'warszawa-centrum',
    orderScenarioCode: 'rep_visit',
    monthlyOrderCount: 7,
    avgBasketValueNet: '1510.75',
    paymentTermDays: 14,
    addresses: [
      {
        label: 'Kuchnia główna',
        line1: 'ul. Przybyszewskiego 56',
        line2: 'Bielany',
        city: 'Warszawa',
        postalCode: '01-849',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.276000',
        longitude: '20.937000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-hotel-wilanow-park',
    companyName: 'Hotel Wilanów Park sp. z o.o.',
    segment: 'hotel',
    taxId: '5217726140',
    email: 'zaopatrzenie@wilanowpark.pl',
    phone: '+48 22 651 33 90',
    contactPerson: 'Dorota Michalska',
    deliveryZoneCode: 'warszawa-obrzeza',
    orderScenarioCode: 'ideal_file',
    monthlyOrderCount: 10,
    avgBasketValueNet: '5340.00',
    paymentTermDays: 30,
    addresses: [
      {
        label: 'Magazyn hotelowy',
        line1: 'ul. Klimczaka 17',
        line2: 'Wilanów',
        city: 'Warszawa',
        postalCode: '02-797',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.165000',
        longitude: '21.090000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-stolowka-ursynowska',
    companyName: 'Stołówka Ursynowska sp. z o.o.',
    segment: 'stolowka',
    taxId: '9512256084',
    email: 'biuro@stolowkaursynowska.pl',
    phone: '+48 22 644 18 32',
    contactPerson: 'Halina Zawadzka',
    deliveryZoneCode: 'warszawa-obrzeza',
    orderScenarioCode: 'email',
    monthlyOrderCount: 7,
    avgBasketValueNet: '1920.00',
    paymentTermDays: 21,
    addresses: [
      {
        label: 'Kuchnia',
        line1: 'ul. Komisji Edukacji Narodowej 36',
        line2: 'Ursynów',
        city: 'Warszawa',
        postalCode: '02-777',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.149000',
        longitude: '21.050000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-piekarnia-bialolecka',
    companyName: 'Piekarnia Białołęcka Chleb i Ziarno sp.j.',
    segment: 'piekarnia',
    taxId: '5241029930',
    email: 'zamowienia@chlebiziarno.pl',
    phone: '+48 22 811 46 05',
    contactPerson: 'Grzegorz Sikora',
    deliveryZoneCode: 'warszawa-obrzeza',
    orderScenarioCode: 'nonstandard_file',
    monthlyOrderCount: 12,
    avgBasketValueNet: '1345.20',
    paymentTermDays: 14,
    addresses: [
      {
        label: 'Zakład produkcyjny',
        line1: 'ul. Modlińska 190',
        line2: 'Białołęka',
        city: 'Warszawa',
        postalCode: '03-119',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.321000',
        longitude: '21.000000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-restauracja-wawerska-zagroda',
    companyName: 'Restauracja Wawerska Zagroda Janusz Król',
    segment: 'restauracja',
    taxId: '9521044789',
    email: 'kontakt@wawerskazagroda.pl',
    phone: '+48 600 317 842',
    contactPerson: 'Janusz Król',
    deliveryZoneCode: 'warszawa-obrzeza',
    orderScenarioCode: 'phone',
    monthlyOrderCount: 5,
    avgBasketValueNet: '1090.00',
    paymentTermDays: 7,
    addresses: [
      {
        label: 'Kuchnia',
        line1: 'ul. Płowiecka 85',
        line2: 'Wawer',
        city: 'Warszawa',
        postalCode: '04-501',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.196000',
        longitude: '21.170000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-catering-ursus',
    companyName: 'Catering Ursus Kuchnia Zakładowa sp. z o.o.',
    segment: 'catering',
    taxId: '5223051178',
    email: 'zamowienia@cateringursus.pl',
    phone: '+48 22 478 92 14',
    contactPerson: 'Sylwia Baran',
    deliveryZoneCode: 'warszawa-obrzeza',
    orderScenarioCode: 'ideal_file',
    monthlyOrderCount: 14,
    avgBasketValueNet: '4980.50',
    paymentTermDays: 21,
    addresses: [
      {
        label: 'Kuchnia produkcyjna',
        line1: 'ul. Gierdziejewskiego 7',
        line2: 'Ursus',
        city: 'Warszawa',
        postalCode: '02-495',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.195000',
        longitude: '20.880000',
        isDefault: true,
      },
      {
        label: 'Kuchnia satelitarna Włochy',
        line1: 'ul. Łopuszańska 38',
        line2: 'Włochy',
        city: 'Warszawa',
        postalCode: '02-232',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.190000',
        longitude: '20.940000',
      },
      {
        label: 'Magazyn chemii',
        line1: 'ul. Warszawska 24',
        city: 'Piastów',
        postalCode: '05-820',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.184000',
        longitude: '20.840000',
      },
    ],
  },
  {
    handle: 'horeca-kawiarnia-marki-dobra-kawa',
    companyName: 'Kawiarnia Dobra Kawa Marki Iwona Sadowska',
    segment: 'kawiarnia',
    taxId: '1251740338',
    email: 'iwona@dobrakawamarki.pl',
    phone: '+48 795 220 461',
    contactPerson: 'Iwona Sadowska',
    deliveryZoneCode: 'warszawa-obrzeza',
    orderScenarioCode: 'sms',
    monthlyOrderCount: 2,
    avgBasketValueNet: '378.40',
    paymentTermDays: 0,
    addresses: [
      {
        label: 'Lokal',
        line1: 'ul. Piłsudskiego 95',
        city: 'Marki',
        postalCode: '05-270',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.320000',
        longitude: '21.106000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-szkola-podstawowa-zabki',
    companyName: 'Szkoła Podstawowa nr 3 w Ząbkach',
    segment: 'szkola',
    taxId: '1250937145',
    email: 'sekretariat@sp3zabki.edu.pl',
    phone: '+48 22 781 60 23',
    contactPerson: 'Małgorzata Wieczorek',
    deliveryZoneCode: 'warszawa-obrzeza',
    orderScenarioCode: 'email',
    monthlyOrderCount: 3,
    avgBasketValueNet: '1275.00',
    paymentTermDays: 30,
    addresses: [
      {
        label: 'Budynek szkoły',
        line1: 'ul. Kościelna 2',
        city: 'Ząbki',
        postalCode: '05-091',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.292000',
        longitude: '21.117000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-hotel-pruszkow-business',
    companyName: 'Hotel Pruszków Business sp. z o.o.',
    segment: 'hotel',
    taxId: '5342218064',
    email: 'zakupy@pruszkowbusiness.pl',
    phone: '+48 22 758 41 77',
    contactPerson: 'Rafał Mazur',
    deliveryZoneCode: 'warszawa-obrzeza',
    orderScenarioCode: 'ideal_file',
    monthlyOrderCount: 9,
    avgBasketValueNet: '3860.00',
    paymentTermDays: 30,
    addresses: [
      {
        label: 'Magazyn hotelowy',
        line1: 'ul. Kraszewskiego 25',
        city: 'Pruszków',
        postalCode: '05-800',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.170400',
        longitude: '20.811700',
        isDefault: true,
      },
      {
        label: 'Obiekt konferencyjny',
        line1: 'ul. Dworcowa 3',
        city: 'Piastów',
        postalCode: '05-820',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.184000',
        longitude: '20.840000',
      },
    ],
  },
  {
    handle: 'horeca-restauracja-konstancinska-willa',
    companyName: 'Restauracja Konstancińska Willa sp. z o.o.',
    segment: 'restauracja',
    taxId: '1230962453',
    email: 'zamowienia@konstancinskawilla.pl',
    phone: '+48 22 754 08 36',
    contactPerson: 'Aleksandra Bąk',
    deliveryZoneCode: 'warszawa-obrzeza',
    orderScenarioCode: 'rep_visit',
    monthlyOrderCount: 6,
    avgBasketValueNet: '2180.60',
    paymentTermDays: 14,
    addresses: [
      {
        label: 'Kuchnia główna',
        line1: 'ul. Warszawska 31',
        city: 'Konstancin-Jeziorna',
        postalCode: '05-520',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.090000',
        longitude: '21.117000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-stolowka-raszynska',
    companyName: 'Stołówka Raszyńska Smak Domu sp. z o.o.',
    segment: 'stolowka',
    taxId: '5342481703',
    email: 'biuro@smakdomu-raszyn.pl',
    phone: '+48 22 720 55 19',
    contactPerson: 'Wiesława Stępień',
    deliveryZoneCode: 'warszawa-obrzeza',
    orderScenarioCode: 'nonstandard_file',
    monthlyOrderCount: 8,
    avgBasketValueNet: '1640.00',
    paymentTermDays: 21,
    addresses: [
      {
        label: 'Kuchnia',
        line1: 'ul. Sportowa 30',
        city: 'Raszyn',
        postalCode: '05-090',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.149000',
        longitude: '20.928000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-hotel-otwock-zdroj',
    companyName: 'Hotel Otwock Zdrój sp. z o.o.',
    segment: 'hotel',
    taxId: '5321894127',
    email: 'zaopatrzenie@otwockzdroj.pl',
    phone: '+48 22 779 63 40',
    contactPerson: 'Bartosz Ostrowski',
    deliveryZoneCode: 'mazowieckie-blisko',
    orderScenarioCode: 'email',
    monthlyOrderCount: 7,
    avgBasketValueNet: '2940.00',
    paymentTermDays: 30,
    addresses: [
      {
        label: 'Magazyn hotelowy',
        line1: 'ul. Kościuszki 12',
        city: 'Otwock',
        postalCode: '05-400',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.105000',
        longitude: '21.261700',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-szpital-otwocki',
    companyName: 'Szpital Powiatowy w Otwocku Dział Żywienia',
    segment: 'szpital',
    taxId: '5321076937',
    email: 'zywienie@szpitalotwock.pl',
    phone: '+48 22 778 26 05',
    contactPerson: 'Elżbieta Krawczyk',
    deliveryZoneCode: 'mazowieckie-blisko',
    orderScenarioCode: 'ideal_file',
    monthlyOrderCount: 8,
    avgBasketValueNet: '4210.00',
    paymentTermDays: 45,
    addresses: [
      {
        label: 'Kuchnia centralna',
        line1: 'ul. Batorego 44',
        city: 'Otwock',
        postalCode: '05-400',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.108000',
        longitude: '21.270000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-piekarnia-grodziska-bochenek',
    companyName: 'Piekarnia Grodziska Bochenek sp.j.',
    segment: 'piekarnia',
    taxId: '5291550818',
    email: 'zamowienia@bochenek-grodzisk.pl',
    phone: '+48 22 755 30 68',
    contactPerson: 'Andrzej Wróbel',
    deliveryZoneCode: 'mazowieckie-blisko',
    orderScenarioCode: 'sms',
    monthlyOrderCount: 9,
    avgBasketValueNet: '760.40',
    paymentTermDays: 7,
    addresses: [
      {
        label: 'Zakład produkcyjny',
        line1: 'ul. 11 Listopada 14',
        city: 'Grodzisk Mazowiecki',
        postalCode: '05-825',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.109400',
        longitude: '20.629400',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-catering-zyrardowski-stol',
    companyName: 'Catering Żyrardowski Stół sp. z o.o.',
    segment: 'catering',
    taxId: '8381762201',
    email: 'zamowienia@zyrardowskistol.pl',
    phone: '+48 46 855 14 27',
    contactPerson: 'Łukasz Sobczak',
    deliveryZoneCode: 'mazowieckie-blisko',
    orderScenarioCode: 'nonstandard_file',
    monthlyOrderCount: 10,
    avgBasketValueNet: '3480.90',
    paymentTermDays: 21,
    addresses: [
      {
        label: 'Kuchnia produkcyjna',
        line1: 'ul. 1 Maja 45',
        city: 'Żyrardów',
        postalCode: '96-300',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.049000',
        longitude: '20.446000',
        isDefault: true,
      },
      {
        label: 'Kuchnia satelitarna',
        line1: 'ul. Bałtycka 2',
        city: 'Grodzisk Mazowiecki',
        postalCode: '05-825',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.109400',
        longitude: '20.629400',
      },
    ],
  },
  {
    handle: 'horeca-restauracja-minska-karczma',
    companyName: 'Restauracja Mińska Karczma sp. z o.o.',
    segment: 'restauracja',
    taxId: '8222190347',
    email: 'biuro@minskakarczma.pl',
    phone: '+48 25 758 41 09',
    contactPerson: 'Damian Olszewski',
    deliveryZoneCode: 'mazowieckie-blisko',
    orderScenarioCode: 'phone',
    monthlyOrderCount: 4,
    avgBasketValueNet: '1370.00',
    paymentTermDays: 14,
    addresses: [
      {
        label: 'Kuchnia',
        line1: 'ul. Warszawska 102',
        city: 'Mińsk Mazowiecki',
        postalCode: '05-300',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.179500',
        longitude: '21.572000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-stolowka-sochaczewska',
    companyName: 'Stołówka Sochaczewska sp. z o.o.',
    segment: 'stolowka',
    taxId: '8371845167',
    email: 'biuro@stolowkasochaczew.pl',
    phone: '+48 46 862 70 33',
    contactPerson: 'Renata Górska',
    deliveryZoneCode: 'mazowieckie-blisko',
    orderScenarioCode: 'email',
    monthlyOrderCount: 5,
    avgBasketValueNet: '2060.00',
    paymentTermDays: 30,
    addresses: [
      {
        label: 'Kuchnia',
        line1: 'ul. Staszica 25',
        city: 'Sochaczew',
        postalCode: '96-500',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.229600',
        longitude: '20.240000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-hotel-serock-nad-zalewem',
    companyName: 'Hotel Serock nad Zalewem sp. z o.o.',
    segment: 'hotel',
    taxId: '5361739284',
    email: 'zakupy@serocknadzalewem.pl',
    phone: '+48 22 782 09 51',
    contactPerson: 'Krzysztof Nowicki',
    deliveryZoneCode: 'mazowieckie-blisko',
    orderScenarioCode: 'ideal_file',
    monthlyOrderCount: 8,
    avgBasketValueNet: '5620.00',
    paymentTermDays: 30,
    addresses: [
      {
        label: 'Magazyn hotelowy',
        line1: 'ul. Pułtuska 47',
        city: 'Serock',
        postalCode: '05-140',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.508000',
        longitude: '21.064000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-kawiarnia-nowodworska-ziarno',
    companyName: 'Kawiarnia Nowodworska Ziarno Paweł Czerwiński',
    segment: 'kawiarnia',
    taxId: '5311644021',
    email: 'pawel@ziarno-nowydwor.pl',
    phone: '+48 604 883 271',
    contactPerson: 'Paweł Czerwiński',
    deliveryZoneCode: 'mazowieckie-blisko',
    orderScenarioCode: 'phone',
    monthlyOrderCount: 2,
    avgBasketValueNet: '295.50',
    paymentTermDays: 0,
    addresses: [
      {
        label: 'Lokal',
        line1: 'ul. Warszawska 30',
        city: 'Nowy Dwór Mazowiecki',
        postalCode: '05-100',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.435800',
        longitude: '20.717000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-zespol-szkol-gora-kalwaria',
    companyName: 'Zespół Szkół w Górze Kalwarii',
    segment: 'szkola',
    taxId: '1231783505',
    email: 'sekretariat@zsgorakalwaria.edu.pl',
    phone: '+48 22 727 34 18',
    contactPerson: 'Waldemar Rutkowski',
    deliveryZoneCode: 'mazowieckie-blisko',
    orderScenarioCode: 'email',
    monthlyOrderCount: 3,
    avgBasketValueNet: '1840.00',
    paymentTermDays: 30,
    addresses: [
      {
        label: 'Kampus przy Pijarskiej',
        line1: 'ul. Pijarska 5',
        city: 'Góra Kalwaria',
        postalCode: '05-530',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '51.980000',
        longitude: '21.214000',
        isDefault: true,
      },
      {
        label: 'Kampus przy Budowlanych',
        line1: 'ul. Budowlanych 14',
        city: 'Góra Kalwaria',
        postalCode: '05-530',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '51.986000',
        longitude: '21.220000',
      },
    ],
  },
  {
    handle: 'horeca-restauracja-grojecki-sad',
    companyName: 'Restauracja Grójecki Sad Halina Duda',
    segment: 'restauracja',
    taxId: '7972256133',
    email: 'kontakt@grojeckisad.pl',
    phone: '+48 48 664 21 70',
    contactPerson: 'Halina Duda',
    deliveryZoneCode: 'mazowieckie-blisko',
    orderScenarioCode: 'rep_visit',
    monthlyOrderCount: 3,
    avgBasketValueNet: '940.30',
    paymentTermDays: 14,
    addresses: [
      {
        label: 'Kuchnia',
        line1: 'ul. Piłsudskiego 47',
        city: 'Grójec',
        postalCode: '05-600',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '51.865000',
        longitude: '20.867000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-hotel-plocki-stary-rynek',
    companyName: 'Hotel Płocki Stary Rynek sp. z o.o.',
    segment: 'hotel',
    taxId: '7743180256',
    email: 'zaopatrzenie@hotelstaryrynek.pl',
    phone: '+48 24 366 18 92',
    contactPerson: 'Izabela Kowalczyk',
    deliveryZoneCode: 'mazowieckie-daleko',
    orderScenarioCode: 'ideal_file',
    monthlyOrderCount: 6,
    avgBasketValueNet: '7180.00',
    paymentTermDays: 30,
    addresses: [
      {
        label: 'Magazyn hotelowy',
        line1: 'ul. Stary Rynek 8',
        city: 'Płock',
        postalCode: '09-400',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.546800',
        longitude: '19.706400',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-szpital-radomski',
    companyName: 'Szpital Radomski Kuchnia Centralna',
    segment: 'szpital',
    taxId: '7962048166',
    email: 'zywienie@szpitalradom.pl',
    phone: '+48 48 361 44 27',
    contactPerson: 'Stanisław Baranowski',
    deliveryZoneCode: 'mazowieckie-daleko',
    orderScenarioCode: 'ideal_file',
    monthlyOrderCount: 6,
    avgBasketValueNet: '9260.00',
    paymentTermDays: 45,
    addresses: [
      {
        label: 'Kuchnia centralna',
        line1: 'ul. Tochtermana 1',
        city: 'Radom',
        postalCode: '26-600',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '51.402700',
        longitude: '21.147100',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-catering-siedlecki-uczta',
    companyName: 'Catering Siedlecki Uczta sp. z o.o.',
    segment: 'catering',
    taxId: '8212389076',
    email: 'zamowienia@uczta-siedlce.pl',
    phone: '+48 25 632 80 15',
    contactPerson: 'Monika Lis',
    deliveryZoneCode: 'mazowieckie-daleko',
    orderScenarioCode: 'email',
    monthlyOrderCount: 5,
    avgBasketValueNet: '2740.80',
    paymentTermDays: 21,
    addresses: [
      {
        label: 'Kuchnia produkcyjna',
        line1: 'ul. Kilińskiego 18',
        city: 'Siedlce',
        postalCode: '08-110',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.167600',
        longitude: '22.290200',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-piekarnia-ostrolecka-klos',
    companyName: 'Piekarnia Ostrołęcka Kłos sp.j.',
    segment: 'piekarnia',
    taxId: '7582120466',
    email: 'biuro@klos-ostroleka.pl',
    phone: '+48 29 764 51 30',
    contactPerson: 'Zbigniew Pietrzak',
    deliveryZoneCode: 'mazowieckie-daleko',
    orderScenarioCode: 'nonstandard_file',
    monthlyOrderCount: 6,
    avgBasketValueNet: '1580.00',
    paymentTermDays: 14,
    addresses: [
      {
        label: 'Zakład produkcyjny',
        line1: 'ul. Gorbatowa 15',
        city: 'Ostrołęka',
        postalCode: '07-410',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '53.085700',
        longitude: '21.572100',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-restauracja-ciechanowska-zamkowa',
    companyName: 'Restauracja Ciechanowska Zamkowa sp. z o.o.',
    segment: 'restauracja',
    taxId: '5661937083',
    email: 'zamowienia@zamkowa-ciechanow.pl',
    phone: '+48 23 672 09 44',
    contactPerson: 'Artur Chmielewski',
    deliveryZoneCode: 'mazowieckie-daleko',
    orderScenarioCode: 'rep_visit',
    monthlyOrderCount: 3,
    avgBasketValueNet: '1760.00',
    paymentTermDays: 14,
    addresses: [
      {
        label: 'Kuchnia',
        line1: 'ul. Warszawska 60',
        city: 'Ciechanów',
        postalCode: '06-400',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.881500',
        longitude: '20.610600',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-stolowka-kozienicka-energetyk',
    companyName: 'Stołówka Kozienicka Energetyk sp. z o.o.',
    segment: 'stolowka',
    taxId: '8121874593',
    email: 'biuro@energetyk-kozienice.pl',
    phone: '+48 48 614 77 20',
    contactPerson: 'Marzena Włodarczyk',
    deliveryZoneCode: 'mazowieckie-daleko',
    orderScenarioCode: 'nonstandard_file',
    monthlyOrderCount: 4,
    avgBasketValueNet: '3150.00',
    paymentTermDays: 30,
    addresses: [
      {
        label: 'Kuchnia zakładowa',
        line1: 'ul. Warszawska 20',
        city: 'Kozienice',
        postalCode: '26-900',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '51.583000',
        longitude: '21.551000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-kawiarnia-sierpecka-retro',
    companyName: 'Kawiarnia Sierpecka Retro Joanna Kubiak',
    segment: 'kawiarnia',
    taxId: '7761563312',
    email: 'joanna@retro-sierpc.pl',
    phone: '+48 663 194 508',
    contactPerson: 'Joanna Kubiak',
    deliveryZoneCode: 'mazowieckie-daleko',
    orderScenarioCode: 'sms',
    monthlyOrderCount: 1,
    avgBasketValueNet: '540.00',
    paymentTermDays: 7,
    addresses: [
      {
        label: 'Lokal',
        line1: 'ul. Piastowska 11',
        city: 'Sierpc',
        postalCode: '09-200',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.858000',
        longitude: '19.674000',
        isDefault: true,
      },
    ],
  },
  {
    handle: 'horeca-restauracja-wegrowski-dwor',
    companyName: 'Restauracja Węgrowski Dwór sp.j.',
    segment: 'restauracja',
    taxId: '8241760923',
    email: 'kontakt@wegrowskidwor.pl',
    phone: '+48 25 792 36 81',
    contactPerson: 'Sebastian Zawisza',
    deliveryZoneCode: 'mazowieckie-daleko',
    orderScenarioCode: 'phone',
    monthlyOrderCount: 3,
    avgBasketValueNet: '1180.00',
    paymentTermDays: 14,
    addresses: [
      {
        label: 'Kuchnia',
        line1: 'ul. Rynek Mariacki 5',
        city: 'Węgrów',
        postalCode: '07-100',
        region: 'mazowieckie',
        countryCode: 'PL',
        latitude: '52.399000',
        longitude: '22.018000',
        isDefault: true,
      },
    ],
  },
]
